apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbit-user-1-permission
  namespace: rabbitmq
spec:
  vhost: "/"
  user: "naEGsDNA5mD6XTz_bMkAPXEruHEDjHM4" # name of the RabbitMQ user
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmqcluster-sample
