---
apiVersion: v1
kind: Secret
metadata:
  name: kobe-user
  namespace: rabbitmq
type: Opaque
data:
  username: a29iZQ==
  password: a29iZTEyMzQ=

---

apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: kobe-user
  namespace: rabbitmq
spec:
  tags:
  - policymaker
  importCredentialsSecret:
    name: kobe-user
  rabbitmqClusterReference:
    name: rabbitmqcluster-sample
---

apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: kobe-user-permission
  namespace: rabbitmq
spec:
  vhost: "/"
  user: "kobe" # name of the RabbitMQ user
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmqcluster-sample
