apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: strimzi-kafka-cluster-kafka-cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: strimzi-kafka-cluster-kafka-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: strimzi-kafka-cluster-kafka
  namespace: strimzi
roleRef:
  kind: ClusterRole
  name: strimzi-kafka-cluster-kafka-cluster-role
  apiGroup: rbac.authorization.k8s.io

