apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimziapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sagarshrestha24/argo-cd.git
    targetRevision: HEAD
    path: kafka
  destination:
    name: in-cluster
    namespace: strimzi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
